wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1648578463
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 13
      4: 3.9.6
      5: 0.12.5
      8:
      - 5
